#!/bin/bash
# precommit hook to make sure no secrets are accidentally leaked
printf "%s" 'running precommit hook...'
WORKTREE=$(git worktree list --porcelain | grep worktree | cut -d ' ' -f2)
exit_status=0
access_key_id_lines=()
secret_access_key_lines=()

for sec in $(cat ~/.aws/credentials | grep aws_secret_access_key | cut -d' ' -f3); do
  for i in $(grep -niR "$sec" "$WORKTREE" 2>&1 | cut -d' ' -f1); do
    secret_access_key_lines+=("$i")
  done
done

for kid in $(cat ~/.aws/credentials | grep aws_access_key_id | cut -d' ' -f3); do
  for i in $(grep -niR "$kid" "$WORKTREE" 2>&1 | cut -d' ' -f1); do
    access_key_id_lines+=("$i")
  done
done

access_key_lines=${#access_key_id_lines[@]}
secret_key_lines=${#secret_access_key_lines[@]}
ct=$(echo "$access_key_lines + $secret_key_lines" | bc)

if [ $ct -gt 0 ]; then
  echo 'AH'
  echo "Found $ct instances of secrets in source, preventing commit:"
  echo
  for a in ${access_key_id_lines[*]}; do
    echo $a | tr ':' '\t'
  done
  for s in ${secret_access_key_lines[*]}; do
    echo $s | tr ':' '\t'
  done
  exit 1
fi
echo done

