on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: source checkout
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: pytest and lint and the other thing
      run: |
        pip install -r requirements-dev.txt
        flake8
        coverage run

    - name: test and lint for python3.7
      run: |
        pip install -r requirements-dev-37.txt
        flake8
        coverage run
      if: ${{ matrix.python-version }} == "3.7"
